format = """
[░▒▓](#a3aed2)\
[ ✙ ](bg:#D8DEE9 fg:#2E3440)\
[](bg:#81A1C1 fg:#D8DEE9)\
$directory\
[](fg:#81A1C1 bg:#3B4252)\
$git_branch\
$git_status\
[](fg:#3B4252 bg:#4C566A)\
$nodejs\
$rust\
$golang\
$c\
$python\
[](fg:#4C566A bg:#2E3440)\
$localip\
[](fg:#2E3440)\
\n$character"""

[directory]
style = "fg:#E5E9F0 bg:#81A1C1"
format = "[ $path ]($style)"
truncation_length = 1

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Videos" = ""
"Desktop" = ""
"GitHub" = ""
"Public" = "󰚧"
"LinuxISOs" = ""
"Applications" = "󰣆"
"Library" = "󱨢"
"Templates" = ""

[git_branch]
symbol = ""
style = "bg:#3B4252"
format = '[[ $symbol $branch ](fg:#81A1C1 bg:#3B4252)]($style)'

[git_status]
style = "bg:#3B4252"
format = '[[($all_status$ahead_behind )](fg:#81A1C1 bg:#3B4252)]($style)'

[nodejs]
symbol = ""
style = "bg:#4C566A"
format = '[[ $symbol ($version) ](fg:#81A1C1 bg:#4C566A)]($style)'

[rust]
symbol = ""
style = "bg:#4C566A"
format = '[[ $symbol ($version) ](fg:#81A1C1 bg:#4C566A)]($style)'

[golang]
symbol = ""
style = "bg:#4C566A"
format = '[[ $symbol ($version) ](fg:#81A1C1 bg:#4C566A)]($style)'

[python]
style = "bg: #4C566A"
format = '[[ $symbol ($version) ](fg #81A1C1 bg:#4C566A)]($style)'

[c]
style = "bg: #4C566A"
format = '[[ $symbol ($version) ](fg: #81A1C1 bg: #4C566A)]($style)'

[localip]
ssh_only = false 
disabled = false
style = "bg:#2E3440"
format = '[[($localipv4)](fg:#D8DEE9 bg:#2E3440)]($style)'

