theme = "base16_transparent"

[editor]
scrolloff = 0
mouse = false
scroll-lines = 5
line-number = "relative"
auto-completion = true
auto-format = true 
auto-info = true
soft-wrap.enable = true 

[editor.lsp]
enable = true 

[editor.cursor-shape]
select = "block"
normal = "bar"
insert = "bar"

