after-login-command = []
after-startup-command = [
    # JankyBorders has a built-in detection of already running process,
    # so it won't be run twice on AeroSpace restart
    'exec-and-forget borders active_color=0xffff4641‰ width=5.0'
]

start-at-login = true
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 20

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# Possible values: (qwerty|dvorak)
key-mapping.preset = 'qwerty'

# Mouse follows focus when focused monitor changes
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

[gaps]
inner.horizontal = 3
inner.vertical =   3
outer.left =       3
outer.bottom =     3
outer.top =        3
outer.right =      3

[mode.main.binding]
# layout setup
alt-e = 'layout tiles'
alt-q = 'layout h_accordion'
alt-shift-space = 'layout floating tiling'
alt-shift-f = 'fullscreen'

# focus
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

# move window
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# join/split window
alt-ctrl-h = 'join-with left'
alt-ctrl-j = 'join-with down'
alt-ctrl-k = 'join-with up'
alt-ctrl-l = 'join-with right'

# resizing
# u/i/o/p follows GlazeWM default setup
alt-u = 'resize width -75'
alt-i = 'resize height -75'
alt-o = 'resize height +75'
alt-p = 'resize width +75'
alt-shift-u = 'resize width -350'
alt-shift-i = 'resize height -350'
alt-shift-o = 'resize height +350'
alt-shift-p = 'resize width +350'

# workspaces
alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'
alt-0 = 'workspace 10'
alt-a = 'workspace 11'
alt-b = 'workspace 12'

ctrl-left = 'workspace --wrap-around prev'
ctrl-right = 'workspace --wrap-around next'
alt-tab = 'workspace-back-and-forth'

# move to workspace
alt-shift-1 = ['move-node-to-workspace 1', 'workspace 1']
alt-shift-2 = ['move-node-to-workspace 2', 'workspace 2']
alt-shift-3 = ['move-node-to-workspace 3', 'workspace 3']
alt-shift-4 = ['move-node-to-workspace 4', 'workspace 4']
alt-shift-5 = ['move-node-to-workspace 5', 'workspace 5']
alt-shift-6 = ['move-node-to-workspace 6', 'workspace 6']
alt-shift-7 = ['move-node-to-workspace 7', 'workspace 7']
alt-shift-8 = ['move-node-to-workspace 8', 'workspace 8']
alt-shift-9 = ['move-node-to-workspace 9', 'workspace 9']
alt-shift-0 = ['move-node-to-workspace 10', 'workspace 10']
alt-shift-a = ['move-node-to-workspace 11', 'workspace 11']
alt-shift-b = ['move-node-to-workspace 12', 'workspace 12']


alt-shift-r = 'reload-config'


# disable hide application
cmd-h = [] # Disable "hide application"
cmd-alt-h = [] # Disable "hide others"

