alias l='eza -lh --icons=auto'                                         # long list
alias ll='eza -lha --icons=auto --sort=name --group-directories-first' # long list all
alias ld='eza -lhD --icons=auto'                                       # long list dirs
alias lt='eza --icons=auto --tree'                                     # list folder as tree
alias la='eza -A'
alias ls='eza --classify --icons=always --group-directories-first'
alias lp='eza -lh --classify --icons=auto --sort=name --group-directories-first'
alias battery='upower -i $(upower -e | grep 'BAT')'
alias cplus='g++ -std=gnu++20 -Wall -Wextra -Wshadow -Wconversion'
alias cpl='g++ -std=gnu++17 -Wall -Wextra -Wshadow -Wconversion'
alias cthis='gcc -std=gnu11 -Wall -Wextra -Wshadow -Wconversion'
alias py3='python3'
alias runc='./a.out'
alias cleaner='rm -rf a.out'
alias add='git add .'
alias status='git status'
alias commit='git commit -m'
alias push='git push'
alias pull='git pull'
alias clone='git clone'
alias branch='git branch'
alias checkout='git checkout'
alias allbranch='git branch -a'
alias merge='git merge'
alias log='git log'
alias stash='git stash'
alias pop='git stash pop'
alias diff='git diff'
alias rebase='git rebase'
alias fetch='git fetch'
alias remote='git remote'
alias cleanup='clear && exit'
alias restore='git restore .'
alias gl='gitleaks'
alias glg='gitleaks git'
alias fast='fastfetch'
alias brewdate='brew update'
alias brewup='brew upgrade'
alias nv='nvim'
alias ve='nvim .'
alias back='z ..'
alias cat='bat'
alias tofu='zathura'
alias story='history | less'
alias pcu='podman-compose up'
alias pcd='podman-compose down'
alias pup='podman compose up'
alias pow='podman compose down'
alias pvp='podman volume prune -f'
alias prebuild='podman compose build --no-cache'
alias dcu='docker compose up'
alias dcd='docker compose down'
alias dvp='docker volume prune -f'
alias dcb='docker compose build --no-cache'
alias dup='docker-compose up'
alias dow='docker-compose down'
alias killz='zellij kill-all-sessions'
alias killer='zellij kill-session'
alias deletez='zellij delete-all-sessions -y'
alias deleter='zellij delete-session'
alias lister='zellij list-sessions'
alias attach='zellij attach'
alias createzellij='zellij attach --create'
alias ig='kitty +kitten icat'
alias lgit='lazygit'
alias startsock='systemctl start docker.socket'
alias stopsock='systemctl stop docker.socket'
alias startdock='systemctl start docker'
alias stopdock='systemctl stop docker'
alias ldock='lazydocker'
alias top='btop'
alias cds='cd .ssh_keys'
alias docks='podman system prune -a --volumes -f'
alias doomsync='~/.config/emacs/bin/doom sync'
alias doomdoctor='~/.config/emacs/bin/doom doctor'
alias doomupgrade='~/.config/emacs/bin/doom upgrade'
alias teamacs='emacs -nw'
alias fu='flatpak update'
alias acli='arduino-cli'
alias txtmd='for f in *.txt; do mv "$f" "${f%.txt}.md"; done'
alias uvenv='uv venv'
alias jrml='ssh -XC mlserver'
alias stml='ssh -XC mlserver2'
alias condavirt='conda create --prefix' #make sure to do "./mynewenv or some other name" and then the specific python version you want for example python=3.9, so an example of the entire command would be conda create --prefix ./mynewenv python=3.9
alias cd='z'
alias ci='zi'
alias np='pnpm'
alias upgrade='sudo dnf upgrade --refresh'
alias ncdu='gdu'
alias huggingface='huggingface-cli'
alias Prod="ssh prod"
alias Test="ssh test"
