[manager]
sort_by = "alphabetical"
show_hidden = false

[[manager.open]]
# Explicitly match the mime type for PDF files
mime = "application/pdf"
run = "zathura \"$1\""

[[manager.open]]
# This is a generic fallback rule.
# It can be for other files you want to open with their default app.
# Note: You can add more specific rules before this one.
mime = "image/*"
run = "feh \"$1\""

[[manager.open]]
# A wildcard rule that uses the system's default program.
# This should be the last rule as it's the most general.
# Yazi will try to use the rules in order from top to bottom.
run = "xdg-open \"$1\""
